#! /bin/bash

# Copyright (c) 2020 Qualcomm Innovation Center, Inc. All Rights Reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

amixer cset name="WSA_CDC_DMA_RX_0 Audio Mixer MultiMedia1" "1"
amixer cset name="WSA_CDC_DMA_RX_0 Channels" "Two"
amixer cset name="WSA RX0 MUX" "AIF1_PB"
amixer cset name="WSA RX1 MUX" "AIF1_PB"
amixer cset name="WSA_RX0 INP0" "RX0"
amixer cset name="WSA_RX1 INP0" "RX0"
amixer cset name="WSA_COMP1 Switch" "1"
amixer cset name="WSA_COMP2 Switch" "1"
amixer cset name="SpkrLeft COMP Switch" "1"
amixer cset name="SpkrLeft BOOST Switch" "1"
amixer cset name="SpkrLeft VISENSE Switch" "1"
amixer cset name="SpkrLeft SWR DAC_Port Switch" "1"
amixer cset name="SpkrRight COMP Switch" "1"
amixer cset name="SpkrRight BOOST Switch" "1"
amixer cset name="SpkrRight VISENSE Switch" "1"
amixer cset name="SpkrRight SWR DAC_Port Switch" "1"
amixer cset name="WSA_RX0 Digital Volume" "84"
amixer cset name="WSA_RX1 Digital Volume" "84"
amixer cset name="MultiMedia1 Mixer TX_CDC_DMA_TX_3" "1"
amixer cset name="TX DEC0 MUX" "MSM_DMIC"
amixer cset name="TX DMIC MUX0" "DMIC0"
amixer cset name="TX_CDC_DMA_TX_3 Channels" "One"
amixer cset name="TX_CDC_DMA_TX_3 SampleRate" "KHZ_48"
amixer cset name="TX_CDC_DMA_TX_3 Format" "S16_LE"
amixer cset name="TX_AIF1_CAP Mixer DEC0" "1"
amixer cset name="TX_DEC0 Volume" "90"
