# Copyright (c) 2020, 2022 Qualcomm Innovation Center, Inc.  All Rights Reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

test: matrix_multiply.cpp
	$(CXX) -o test matrix_multiply.cpp -lOpenCL -I /usr/include/qrx210


clean:
	rm test
