# Copyright (c) 2020 Qualcomm Innovation Center, Inc.  All Rights Reserved.
# SPDX-License-Identifier: BSD-3-Clause-Clear

test: matrix_multiply.cpp
	g++ -o test matrix_multiply.cpp -lOpenCL -I /usr/include/qrb5165


clean:
	rm test
